In [ ]:
#LIBRARIES IN PYTHON
#1 NUMPY

#why use NumPy?
#numPy provides effcient storage
#it also provides better way of handling data for processing.
#it is fast.
#it is easy to learn.
#numPy uses relatively less memory to store data


In [ ]:
import numpy as np
myarr= np.array([[3,6,32,7]], np.int8)   #np.int8 is just a memory size, through this we have control over memory management.
myarr[0,0]       #to access any element of the array.
myarr[0,1]        
myarr.shape         #for more jnkari about myarr, shape mil jayega
myarr.dtype         #kis type ka bana hua h

dtype('int8')

In [ ]:
import numpy as np
myarr=np.array([[3,2,1]],np.int32)
myarr[0,1]=45   #changed the elemnt at 0,1 position.
myarr

array([[ 3, 45,  1]], dtype=int32)

In [ ]:
#array creation methods: numpy array ko create krne ke ky ky tareeke hote h.
#1.conversion from other python structures.e.g lists or tuples
listarray= np.array([[1,2,3],[4,5,6],[0,3,1]])
listarray
#listarray.shape

array([[1, 2, 3],
       [4, 5, 6],
       [0, 3, 1]])

In [ ]:
listarray.shape

(3, 3)

In [ ]:
listarray.dtype

dtype('int64')

In [ ]:
listarray.size

9

In [ ]:
#using a dictionary
np.array({34,43,54})

array({34, 43, 54}, dtype=object)

In [ ]:
#2.intrinsic numpy array creation objects.
import numpy as np
zeros=np.zeros((2,5))  #zeros func apko ek zeros ki array bana ke deta hai.
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
zeros.shape

(2, 5)

In [ ]:
zeros.size

10

In [ ]:
zeros.dtype

dtype('float64')

In [ ]:
import numpy as np
rng=np.arange(15)      #arange function apko ek numpy array bana ke deta hai.
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
import numpy as np
lemon= np.arange(100)
lemon

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [ ]:
import numpy as np
sqeeze= np.zeros(((3,3)))
sqeeze


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
import numpy as np
lspace=np.linspace(1,50,10) #linspace func apko linearly spaced elements bana k deta hai
                            #(1,50,10) means 1 se lekr 50 k beech m 10 elements linerly spaced.
lspace                            

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [ ]:
import numpy as np
emp=np.empty((4,3))  #empty func gives you a khali array of (whatever) and all elements will be random.
emp

array([[2.50502033e-316, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [ ]:
import numpy as np
emp_like=np.empty_like(lspace) #empty_like func kisi bhi purane array k size ko 
emp_like                        #copy krke uski empty array bana deta h. 
                               #for efficiency.
                               

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [ ]:
import numpy as np
ide=np.identity(45)
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [ ]:
ide.shape

(45, 45)

In [ ]:
ide.size

2025

In [ ]:
import numpy as np
arr= np.arange(99)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [ ]:
arr.reshape(3,33)  #reshape func allows us to break an array into diff parts
                   #(3,33) means break it into 3 parts each till 33 elements

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [ ]:
import numpy as np
aaa=np.arange(125)
aaa

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124])

In [ ]:
import numpy as np
aaa=np.arange(120)
aaa

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119])

In [ ]:
aaa.reshape(4,30)

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
         13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
         26,  27,  28,  29],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,
         43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,
         56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,
         73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,
         86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102,
        103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115,
        116, 117, 118, 119]])

In [ ]:
aaa.ravel()   #ravel func to get back a array in default shape. 

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119])

In [ ]:
#axis in NumPy
#1 dimensional has 1 axis, axis0. kyuki yaha pr sirf ek hi axis hai axis0 to yaha hum axis1 pr 
#kaam nahi kr skte kyuki vo exist hi nahi krta hai.
#2D has 2 axes, axis0 and axis1 [axis0,axis1]



In [ ]:
import numpy as np
x= [[1,2,3],[4,5,6],[7,1,0]]
ar=np.array(x)
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [ ]:
ar.sum(axis=0)   #axis0 is vertical and horizontal is axis1. this is the sum of axis0.

array([12,  8,  9])

In [ ]:
import numpy as np
a=[[1,2,3],[8,9,7],[4,4,4]]
abc=np.array(a)
abc

array([[1, 2, 3],
       [8, 9, 7],
       [4, 4, 4]])

In [ ]:
abc.sum(axis=1)

array([ 6, 24, 12])

In [ ]:
abc.T   #T transposes an array. transpose means row will become column and vice-versa.

array([[1, 8, 4],
       [2, 9, 4],
       [3, 7, 4]])

In [ ]:
abc.flat  #flat func gives an iterater.
          

In [ ]:
for item in abc.flat:
  print(item)       #get all items of the array.

1
2
3
8
9
7
4
4
4


In [ ]:
abc.ndim  #ndim func gives the number of dimensions of the array.

2

In [ ]:
import numpy as np
abc= np.array((([1,1,1],[2,2,2],[3,3,3])))
abc

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [ ]:
abc.ndim

2

In [ ]:
abc.size

9

In [ ]:
abc.nbytes

72

In [ ]:
import numpy as np
one=np.array([1,3,4,634,2])
one.argmax()   #this argmax is a function, pehle jab () nhi laga rhe the tb we were using them 
               #as attributes.
               #argmax func gives us the index at which the max value is put.

3

In [ ]:
one.argmin() #argmin gives the index where the min value is inserted.

0

In [ ]:
one.argsort() #argsort will give indexes of values in increasing order.


array([0, 4, 1, 2, 3])

In [ ]:
import numpy as np
aaa= np.array((([1,1,1],[2,2,2],[3,3,3])))
aaa

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [ ]:
aaa.argmin()

0

In [ ]:
aaa.argmax()

6

In [ ]:
aaa.argmax(axis=0)
           

array([2, 2, 2])

In [ ]:
aaa.argmax(axis=1)

array([0, 0, 0])

In [ ]:
aaa.argsort(axis=0)

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]])

In [ ]:
aaa.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [ ]:
aaa.ravel()

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [ ]:
aaa.reshape(9,1)

array([[1],
       [1],
       [1],
       [2],
       [2],
       [2],
       [3],
       [3],
       [3]])

In [ ]:
#mathematical operations in NumPy. Matrix mostly.
import numpy as np
bbb=np.array(([1,21,1],[4,0,6],[8,1,0]))
bbb

array([[ 1, 21,  1],
       [ 4,  0,  6],
       [ 8,  1,  0]])

In [ ]:
aaa+bbb

array([[ 2, 22,  2],
       [ 6,  2,  8],
       [11,  4,  3]])

In [ ]:
aaa*bbb

array([[ 1, 21,  1],
       [ 8,  0, 12],
       [24,  3,  0]])

In [ ]:
#numpy allows us to do matrix operations, which is not possible for a list.

In [ ]:
import numpy as np
qqq=np.sqrt(bbb)  #sqrt func allows the square root.
qqq


array([[1.        , 4.58257569, 1.        ],
       [2.        , 0.        , 2.44948974],
       [2.82842712, 1.        , 0.        ]])

In [ ]:
qqq.sum() #sum of all elements.

14.860492562485208

In [ ]:
qqq.max()  #max func gives the max value from the array.

4.58257569495584

In [ ]:
qqq.min()  #min func gives the min value from the array.

0.0

In [ ]:
np.count_nonzero(aaa) #count_nonzero func gives the number of how many nonzero elements we have

9

In [ ]:
import sys
py_abc=[0,11,2,3,4]
np_abc=np.array(py_abc)
sys.getsizeof(1)*len(py_abc)

140

In [ ]:
np_abc.itemsize*np_abc.size

40